package problem2

/*
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
*/


func EvenFibonacci () (int) {
  var sequence = []int{1}
  var next_in_sequence int
  var even_values_sum int
  for i := 1; i == i; i++ {
    if len(sequence) == 1 {
      next_in_sequence = sequence[len(sequence) - 1] + sequence[len(sequence) - 1] 
    } else {
      next_in_sequence = sequence[len(sequence) - 2] + sequence[len(sequence) - 1]
    }
    if next_in_sequence % 2 == 0 {
      even_values_sum += next_in_sequence
    }
    if next_in_sequence > 4000000 {
      break
    }
    sequence = append(sequence, next_in_sequence)
  }
  return even_values_sum
}
